services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  postgres:
      image: postgres:17-alpine
      container_name: postgres
      environment:
        POSTGRES_USER: sa
        POSTGRES_PASSWORD: Saurabh@51
        POSTGRES_DB: coding_helper
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped  

volumes:
  redis_data:
  postgres_data: